cora:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 1.0e-04
  tau_g: 0.4
  tau_n: 0.9
  w_g: 0.5
  epochs: 150
  eval_lr: 0.001
  eval_epochs: 200
  dropout_rate: 0.4
  noise_std: 0.4
  batch_size1: null
  batch_size2: null
  n_w_wn: 1.0
  n_w_wp: 1.0
  g_w_wn: 1.0
  g_w_wp: 1.0
  
citeseer:
  num_layers: 1
  hid_dim: 1024
  proj_dim: 1024
  lr: 1.0e-04
  weight_decay: 5.0e-04
  tau_g: 0.8
  tau_n: 0.9
  w_g: 0.5
  epochs: 150
  eval_lr: 0.001
  eval_epochs: 100
  dropout_rate: 0.9
  noise_std: 0.6
  batch_size1: null
  batch_size2: null
  n_w_wn: 0.7
  n_w_wp: 0.6
  g_w_wn: 0.4
  g_w_wp: 0.3

pubmed:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 5.0e-04
  weight_decay: 1.0e-04
  tau_g: 0.8
  tau_n: 0.3
  w_g: 1.0
  epochs: 500
  eval_lr: 0.01
  eval_epochs: 300
  dropout_rate: 0.5
  noise_std: 0.1
  batch_size1: null
  batch_size2: null
  n_w_wn: 1.0
  n_w_wp: 1.0
  g_w_wn: 1.0
  g_w_wp: 1.0

cora_coauthor:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-04
  weight_decay: 5.0e-04
  tau_g: 0.5
  tau_n: 0.7
  w_g: 1.0
  epochs: 300
  eval_lr: 0.001
  eval_epochs: 300
  dropout_rate: 0.3
  noise_std: 0.4
  batch_size1: null
  batch_size2: null
  n_w_wn: 1.0
  n_w_wp: 0.6
  g_w_wn: 0.9
  g_w_wp: 0.6

dblp_coauthor:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 5.0e-04
  tau_g: 0.2
  tau_n: 0.9
  w_g: 0.5
  epochs: 300
  eval_lr: 0.01
  eval_epochs: 100
  dropout_rate: 0.6
  noise_std: 0.3
  batch_size1: 8192
  batch_size2: 4096
  n_w_wn: 0.3
  n_w_wp: 0.8
  g_w_wn: 1.0
  g_w_wp: 0.7

zoo:
  num_layers: 1
  hid_dim: 256
  proj_dim: 256
  lr: 1.0e-03
  weight_decay: 1.0e-04
  tau_g: 0.6
  tau_n: 0.2
  w_g: 0.5
  epochs: 100
  eval_lr: 0.005
  eval_epochs: 300
  dropout_rate: 0.0
  noise_std: 0.5
  batch_size1: null
  batch_size2: null
  n_w_wn: 0.9
  n_w_wp: 0.9
  g_w_wn: 0.3
  g_w_wp: 0.5

20newsW100:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-04
  weight_decay: 1.0e-05
  tau_g: 0.4
  tau_n: 0.8
  w_g: 0.5
  epochs: 200
  eval_lr: 0.01
  eval_epochs: 300
  dropout_rate: 0.7
  noise_std: 0.9
  batch_size1: null
  batch_size2: null
  n_w_wn: 0.4
  n_w_wp: 0.7
  g_w_wn: 1.0
  g_w_wp: 1.0

Mushroom:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 5.0e-04
  tau_g: 0.1
  tau_n: 0.2
  w_g: 1.0
  epochs: 300
  eval_lr: 0.01
  eval_epochs: 100
  dropout_rate: 0.0
  noise_std: 0.1
  batch_size1: null
  batch_size2: null
  n_w_wn: 0.5
  n_w_wp: 0.3
  g_w_wn: 0.6
  g_w_wp: 0.8

NTU2012:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 5.0e-04
  weight_decay: 5.0e-04
  tau_g: 0.4
  tau_n: 0.6
  w_g: 2.0
  epochs: 200
  eval_lr: 0.005
  eval_epochs: 100
  dropout_rate: 0.2
  noise_std: 0.1
  batch_size1: null
  batch_size2: null
  n_w_wn: 0.9
  n_w_wp: 0.9
  g_w_wn: 0.6
  g_w_wp: 0.6

ModelNet40:
  num_layers: 1
  hid_dim: 512
  proj_dim: 512
  lr: 1.0e-03
  weight_decay: 5.0e-04
  tau_g: 0.4
  tau_n: 0.8
  w_g: 1.0
  epochs: 150
  eval_lr: 0.005
  eval_epochs: 300
  dropout_rate: 0.2
  noise_std: 0.1
  batch_size1: null
  batch_size2: null
  n_w_wn: 0.4
  n_w_wp: 0.9
  g_w_wn: 0.3
  g_w_wp: 0.6
